Add SqlRepository<TIgar>
lvivdotnet/IgarBot pull request #1
Opened 2020-04-15 16:47 UTC by d1mnewz

Signed-off-by: dmytro.zhluktenko <dmytro.zhluktenko@eleks.com>

2020-04-15 16:49 UTC, AshasTob commented on src/IgarBot/IRepository.cs
> +        TIgar GetIgar();
Method misses async implementation GetIgarAsync

2020-04-15 16:50 UTC, d1mnewz commented
@bruceBayne PTAL

2020-04-15 16:51 UTC, d1mnewz commented on src/IgarBot/Igar.cs
> +            return Guid.NewGuid();
We need to introduce sync tool here - any ideas - Semaphores, Mutex?...

2020-04-15 16:51 UTC, AshasTob requested changes

2020-04-15 16:51 UTC, AshasTob commented on src/IgarBot/Igar.cs
> +    public class Igar
Make this class a singleton with private constructor. There can be only one Igar. Also make sure that we have singleton implemented in our repo.

2020-04-15 16:51 UTC, AshasTob commented on src/IgarBot/SqlRepository.cs
> +            // TODO: AbstractIgarFactory
I like this

2020-04-15 16:51 UTC, d1mnewz commented on src/IgarBot/SqlRepository.cs
> +            // TODO: AbstractIgarFactory
@AshasTob please take over the implementation of this factory since this is too complex for me.

2020-04-15 16:52 UTC, d1mnewz commented on src/IgarBot/IRepository.cs
> +        TIgar GetIgar();
No.

2020-04-16 08:44 UTC, YuraDubensky commented on src/IgarBot/Igar.cs
> +        public static Igar IgarInstance { get; }
Property is not initialized, will result in NullReferenceExcetion

2020-04-16 09:02 UTC, d1mnewz commented on src/IgarBot/Igar.cs
> +        public static Igar IgarInstance { get; }
by design?

2020-04-16 12:06 UTC, roman-lemko commented on src/IgarBot/Igar.cs
> +            return Guid.NewGuid();
let's start with a lock at least?
I'm really nervous about race conditions.

btw, where are our race conditions??

2020-04-16 17:47 UTC, olehrechukh approved these changes

2020-12-31 11:35 UTC, closed without merging